[package]
name = "sskr"
version = "0.1.0"
edition = "2021"
description = "Sharded Secret Key Reconstruction (SSKR) for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-sskr-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/sskr"

[dependencies]
bc-crypto = "0.1.0"
bc-shamir = "0.1.0"

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
version-sync = "0.9"
