[package]
name = "sskr"
version = "0.4.2"
edition = "2021"
description = "Sharded Secret Key Reconstruction (SSKR) for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-sskr-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/sskr"

[dependencies]
bc-rand = "^0.2.1"
bc-shamir = "^0.4.0"

thiserror = "^1.0.48"

[dev-dependencies]
hex-literal = "^0.4.1"
hex = "^0.4.3"
version-sync = "^0.9.0"
rand = "^0.8.5"
